default_settings: ~

behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048        # doubled batch size to improve convergence
      buffer_size: 20480      # doubled buffer size to improve stability, X10 ratio
      learning_rate: 0.003    # increased learning rate to improve convergence, from 0.0003
      beta: 0.01             # increased from 0.005 to 0.01 to improve exploration/randomness
      epsilon: 0.2
      lambd: 0.95            # adaptation rate
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: constant  # made constant to improve stability
    network_settings:
      normalize: false        # no normalization, discrete action space
      hidden_units: 256       # increased from 128 to 256 to improve complexity
      num_layers: 3           # increased from 2 to 3 to improve complexity
      vis_encode_type: simple
      memory:
        sequence_length: 128  # added memory to save progress, LSTMs   
        memory_size: 256      # increased from 128 to 256 to make replay buffer more robust
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256      # increased from 128 to 256 to improve complexity
          num_layers: 4          # increased from 2 to 4 to improve complexity
          vis_encode_type: simple
          memory: ~
          goal_conditioning_type: hyper
          deterministic: false
    init_path: ~
    keep_checkpoints: 5
    checkpoint_interval: 5000000    # increased from 500000 to 5000000 to improve performance
    max_steps: 5000000              # increased from 500000 to 5000000 to improve performance
    time_horizon: 64
    summary_freq: 50000
    threaded: true              # added threaded to improve performance
    self_play: ~
    behavioral_cloning: ~

env_settings:
  env_path: ~
  env_args: ~
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 0
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60

engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false

environment_parameters: ~

checkpoint_settings:
  run_id: PREFINAL_TASK
  initialize_from: ~
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results

torch_settings:
  device: ~

debug: false
